src/Smartproduct.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Smartproduct.Interface.Category;
using Smartproduct.Model.Category;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Smartproduct.Web.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {

        Category category = new Category();
        private readonly ICategory _categoryRouter;
        public CategoryController(ICategory categoryRouter)
        {
            _categoryRouter = categoryRouter;
        }

        [HttpGet]
        public async Task<IActionResult> Currentcategories()
        {
            return View(await _categoryRouter.GetAllCategories());
        }

        [HttpGet]
        public IActionResult Newcategory()
        {
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Newcategory(Category category)
        {
            var check1 = await _categoryRouter.DuplicateCategory(category.Name);
            var check2 = await _categoryRouter.CheckIfCategoryCodeExist(category.CategoryCode);

            do
            {
                if(check1 || check2)
                {
                    if (check1)
                    {
                        category.Errormessage1 = $"Category name chosen";
                    }
                    if (check2)
                    {
                        category.Errormessage3 = $"Category code chosen";
                    }
                    if (!CategoryValidator.IsValidCategoryCode(category.CategoryCode))
                    {
                        category.Errormessage2 = $"Format: ABC###      E.g      ABC123";
                    }
                    return View(category);
                }
                else
                {
                    category.CreatedBy = User.Identity.Name;
                    var result = await _categoryRouter.Post(category);
                    return RedirectToAction("Currentcategories");
                }
            }
            while (check1 == false && check2 == false);
        }

        [HttpGet]
        public async Task<IActionResult> Editcategory(int CategoryId)
        {
            category = await _categoryRouter.GetCategoryById(CategoryId);
            return View(category);
        }
        [HttpPost]
        public async Task<IActionResult> Editcategory(Category category)
        {
            category.CreatedBy = User.Identity.Name;
            var result = await _categoryRouter.Put(category);
            return RedirectToAction("Currentcategories");
        }
    }
}

src/Smartproduct.Web/Controllers/FileController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Smartproduct.Interface.File;
using Smartproduct.Interface.Product;
using Smartproduct.Web.Models;
using Smartproduct.Web.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace Smartproduct.Web.Controllers
{
    [Authorize]
    public class FileController : Controller
    {
        FileViewModel fvm = new FileViewModel();
        private readonly IFile _fileRouter;
        private readonly IProduct _productRouter;
        public FileController(IFile fileRouter, IProduct productRouter)
        {
            _fileRouter = fileRouter;
            _productRouter = productRouter;
        }

        [HttpGet]
        public async Task<IActionResult> Files()
        {
            fvm.Files = await _fileRouter.GetAllFiles();
            fvm.Files = fvm.Files.Where(x => x.CreatedBy == User.Identity.Name).ToList();
            if (fvm.Files != null)
                fvm.CountFiles = fvm.Files.Count();
            else
                fvm.CountFiles = 0;

            return View(fvm);
        }

        [HttpPost]
        public async Task<IActionResult> Files(IFormFile File)
        {
            var products = await _productRouter.GetAllProducts();
            await _fileRouter.Insert(FileHelper.UploadExcel(File, User.Identity.Name, null));
            await _productRouter.Bulkinsert(FileHelper.GetDataFromExcel(File,products,User.Identity.Name));
            return RedirectToAction("Currentproducts", "Product");
        }

        [HttpGet]
        public async Task<IActionResult> Download(int FileId)
        {
            var documents = await _fileRouter.GetFileById(FileId);
            MemoryStream ms = new MemoryStream(documents.FileData);
            return File(documents.FileData, documents.FileContentType,documents.FileName);
        }

    }
}

src/Smartproduct.Web/Views/Shared/_LayoutHeader.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{ 

    var headings = ViewData.ContainsKey("HeadingDetails") ? ViewData["HeadingDetails"].ToString() : string.Empty;
    var headingSubTittle = ViewData.ContainsKey("HeadingSubTittle") ? ViewData["HeadingSubTittle"].ToString() : string.Empty;
    var headingSubDetails = ViewData.ContainsKey("HeadingSubDetails") ? ViewData["HeadingSubDetails"].ToString() : string.Empty;

    var hrefLink = ViewData.ContainsKey("hrefLink") ? ViewData["hrefLink"].ToString() : "#";
    var action = ViewData.ContainsKey("action") ? ViewData["action"].ToString() : string.Empty;
    var btnIcon = ViewData.ContainsKey("btnIcon") ? ViewData["btnIcon"].ToString() : string.Empty;
}


<div class="content container-fluid">
    <!-- Page Header -->
    <div class="page-header">
        <div class="row align-items-end">
            <div class="col-sm mb-2 mb-sm-0">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-no-gutter">
                        <li class="breadcrumb-item"><a class="breadcrumb-link" href="javascript:;">@headings</a></li>
                        <li class="breadcrumb-item"><a class="breadcrumb-link" href="javascript:;">@headingSubTittle</a></li>

                    </ol>
                </nav>

                <h1 class="page-header-title">@headingSubDetails</h1>
            </div>

            <div class="col-sm-auto">
                @if (!string.IsNullOrEmpty(hrefLink))
                {
                    <a class="btn btn-sm btn-primary mr-2" href=@hrefLink>
                        <i class="@btnIcon mr-1"></i> @action
                    </a>
                }
            </div>
        </div>
        <!-- End Row -->
    </div>
    <!-- End Page Header -->
</div>

src/Smartproduct.Web/Views/Shared/_LayoutMenu.cshtml
<div class="navbar-nav-wrap-content-left collapse navbar-collapse" id="navbarNavMenu">
    <div class="navbar-body">
        <ul class="navbar-nav flex-grow-1">
            <li class="hs-has-sub-menu">
                <a id="pagesDropdown" class="hs-mega-menu-invoker navbar-nav-link nav-link nav-link-toggle" href="javascript:;" aria-haspopup="true" aria-expanded="false" aria-labelledby="navLinkPagesDropdown-Users">
                    <i class="fas fa-house nav-icon"></i> Categories
                </a>

                <!-- Dropdown -->
                <ul id="navLinkPagesDropdown-Users" class="hs-sub-menu dropdown-menu dropdown-menu-lg hs-sub-menu-desktop-lg animated" aria-labelledby="pagesDropdown-Users" style="min-width: 16rem; animation-duration: 300ms;">
                    <li>
                        <a class="dropdown-item" href="@Url.Action("Newcategory", "Category")">
                            <span class="tio-circle-outlined nav-indicator-icon"></span> New
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="@Url.Action("Currentcategories", "Category")">
                            <span class="tio-circle-outlined nav-indicator-icon"></span> Current Categories
                        </a>
                    </li>
                </ul>
                <!-- End Dropdown -->
            </li>
            <li class="hs-has-sub-menu">
                <a id="pagesDropdown" class="hs-mega-menu-invoker navbar-nav-link nav-link nav-link-toggle" href="javascript:;" aria-haspopup="true" aria-expanded="false" aria-labelledby="navLinkPagesDropdown-Users">
                    <i class="fas fa-list  nav-icon"></i> Products
                </a>

                <!-- Dropdown -->
                <ul id="navLinkPagesDropdown-Users" class="hs-sub-menu dropdown-menu dropdown-menu-lg hs-sub-menu-desktop-lg animated" aria-labelledby="pagesDropdown-Users" style="min-width: 16rem; animation-duration: 300ms;">
                    <li>
                        <a class="dropdown-item" href="@Url.Action("Newproduct", "Product")">
                            <span class="tio-circle-outlined nav-indicator-icon"></span> New
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="@Url.Action("Currentproducts", "Product")">
                            <span class="tio-circle-outlined nav-indicator-icon"></span> Current Products
                        </a>
                    </li>
                </ul>
                <!-- End Dropdown -->
            </li>

            <li class="hs-has-sub-menu">
                <a id="pagesDropdown" class="hs-mega-menu-invoker navbar-nav-link nav-link nav-link-toggle" href="javascript:;" aria-haspopup="true" aria-expanded="false" aria-labelledby="navLinkPagesDropdown-Users">
                    <i class="fas fa-user nav-icon"></i> Downloads
                </a>

                <!-- Dropdown -->
                <ul id="navLinkPagesDropdown-Users" class="hs-sub-menu dropdown-menu dropdown-menu-lg hs-sub-menu-desktop-lg animated" aria-labelledby="pagesDropdown-Users" style="min-width: 16rem; animation-duration: 300ms;">
                    <li>
                        <a class="dropdown-item" href="@Url.Action("Files", "File")">
                            <span class="tio-circle-outlined nav-indicator-icon"></span> Files
                        </a>
                    </li>
                </ul>
                <!-- End Dropdown -->
            </li>

        </ul>
    </div>
</div>

src/Smartproduct.Web/Views/Shared/_LayoutUserPortal.cshtml
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <!-- Required Meta Tags Always Come First -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title -->
    <title>Product Manager</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/favicon.ico">

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="~/front-dashboard-v1.1/dist/assets/css/vendor.min.css">
    <link rel="stylesheet" href="~/front-dashboard-v1.1/dist/assets/vendor/icon-set/style.css">

    <!-- CSS Front Template -->
    <link rel="stylesheet" href="~/front-dashboard-v1.1/dist/assets/css/theme.min.css?v=1.0">
</head>

<body class="d-flex align-items-center min-h-100">
    <!-- ========== END HEADER ========== -->
    <!-- ========== MAIN CONTENT ========== -->
    <main id="content" role="main" class="main pt-0">
        <!-- Content -->
        <div class="container-fluid px-3">
            <div class="row">
                <!-- Cover -->
                <div class="col-lg-6 d-none d-lg-flex justify-content-center align-items-center min-vh-lg-100 position-relative bg-light px-0">
                    <!-- Logo & Language -->
                    <!-- End Logo & Language -->

                    <div style="max-width: 23rem;">
                        <div class="text-center mb-5">
                            <img class="img-fluid" src="~/front-dashboard-v1.1/dist/assets/svg/illustrations/chat.svg" alt="Image Description" style="width: 12rem;">
                        </div>

                        <!-- List Checked -->
                        <ul class="list-checked list-checked-lg list-checked-primary list-unstyled-py-4">
                            <li class="list-checked-item">
                                <span class="d-block font-weight-bold mb-1 text-wrap">Whats is 'Product'</span>
                                A product is the item offered for sale. A product can be a service or an item. It can be physical or in virtual or cyber form. Every product is made at a cost and each is sold at a price. The price that can be charged depends on the market, the quality, the marketing and the segment that is targeted. Each product has a useful life after which it needs replacement, and a life cycle after which it has to be re-invented. In FMCG parlance, a brand can be revamped, re-launched or extended to make it more relevant to the segment and times, often keeping the product almost the same.
                            </li>

                            <li style="list-style:none"><center><h2 class="display-4 text-danger">Product Manager</h2></center></li>
                        </ul>
                        <!-- End List Checked -->
                        <!-- End Row -->
                    </div>
                </div>
                <!-- End Cover -->

                @RenderBody()
            </div>
            <!-- End Row -->
        </div>
        <!-- End Content -->
    </main>
    <!-- ========== END MAIN CONTENT ========== -->
    <!-- JS Implementing Plugins -->
@*<script src="~/front-dashboard-v1.1/dist/assets/js/vendor.min.js"></script>*@
<script src="~/front-dashboard-v1.1/dist/assets/vendor/jquery/dist/jquery.min.js"></script>
<script src="~/front-dashboard-v1.1/dist/assets/vendor/jquery-migrate/dist/jquery-migrate.min.js"></script>
<script src="~/front-dashboard-v1.1/dist/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/front-dashboard-v1.1/dist/assets/vendor/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/front-dashboard-v1.1/dist/assets/js/theme.min.js"></script>

    <!-- JS Front -->
<script src="~/front-dashboard-v1.1/dist/assets/js/theme.min.js"></script>
<script src="~/front-dashboard-v1.1/dist/assets/vendor/hs-toggle-password/dist/js/hs-toggle-password.js"></script>
<script src="~/front-dashboard-v1.1/src/assets/js/hs.validation.min.js"></script>

    <!-- JS Plugins Init. -->
    <script>
        $(document).on('ready', function () {
            // INITIALIZATION OF SHOW PASSWORD
            // =======================================================
            $('.js-toggle-password').each(function () {
                new HSTogglePassword(this).init();
            });


            // INITIALIZATION OF FORM VALIDATION
            // =======================================================
            $('.js-validate').each(function () {
                $.HSCore.components.HSValidation.init($(this));
            });


            // INITIALIZATION OF SELECT2
            // =======================================================
            //$('.js-select2-custom').each(function () {
            //    var select2 = $.HSCore.components.HSSelect2.init($(this));
            //});
        });
    </script>

@await RenderSectionAsync("scripts", false)


<!-- IE Support -->
    <script>
    @{ var url = $"{Context.Request.PathBase}/front-dashboard-v1.1/dist/assets/vendor/babel-polyfill/polyfill.min.js"; }
    if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) document.write('<script src="@url"><\/script>');    </script>
</body>
</html>